#let entry-list = (
  (
    key: "miqa",
    short: "MIQA",
    long: "Medical Imaging Quality Assessment",
    group: "Abbreviations",
  ),
  (
    key: "em",
    short: "EM",
    long: "Electron Microscopy",
    group: "Abbreviations",
  ),
  (
    key: "ai",
    short: "AI",
    long: "Artificial Intelligence",
    group: "Abbreviations",
  ),
  (
    key: "tp",
    short: "TP",
    long: "true positive",
    group: "Abbreviations",
  ),
  (
    key: "fp",
    short: "FP",
    long: "false positive",
    group: "Abbreviations",
  ),
  (
    key: "fn",
    short: "FN",
    long: "false negative",
    group: "Abbreviations",
  ),
  (
    key: "tn",
    short: "TN",
    long: "true negative",
    group: "Abbreviations",
  ),
  (
    key: "mri",
    short: "MRI",
    long: "Magnetic Resonance Imaging",
    group: "Abbreviations",
  ),
  (
    key: "ce",
    short: "CE",
    long: "Cross Entropy",
    group: "Abbreviations",
  ),
  (
    key: "cnn",
    short: "CNN",
    long: "Convolutional Neural Network",
    group: "Abbreviations",
  ),
  (
    key: "tda",
    short: "TDA",
    long: "Topological Data Analysis",
    group: "Abbreviations",
  ),
  (
    key: "edt",
    short: "EDT",
    long: "Euclidean Distance Transform",
    group: "Abbreviations",
  ),
  (
    key: "wmh",
    short: "WMH",
    long: "White Matter Hyperintensity",
    group: "Abbreviations",
  ),
  (
    key: "assd",
    short: "ASSD",
    long: "Average Symmetric Surface Distance",
    description: [An instance-wise metric that denotes the average distances of the prediction surface to the ground truth surface. Lower is considered better.],
    group: "Metrics",
  ),
  (
    key: "cedi",
    short: "CEDI",
    long: "Center Distance",
    description: [An instance-wise metric that denotes the distance of the prediction centroid to the ground truth centroid. Lower is considered better.],
    group: "Metrics",
  ),
  (
    key: "fbeta",
    short: [$F_beta$],
    description: [A measure using a positive real factor $beta$ to calculate the weighted harmonic mean between precision and recall. Higher is considered better.],
    group: "Metrics",
  ),
  (
    key: "R",
    short: $R$,
    long: [${R_1, R_2, dots, R_n}$],
    description: [The set of $n$ regions in an image, each of which contains exactly one seed instance],
    group: "Mathematical Notations and Definitions",
  ),
  (
    key: "L",
    short: $"L": Omega mapsto {0,1}$,
    description: [The binary label function that maps a pixel in the image domain to a binary value],
    group: "Mathematical Notations and Definitions",
  ),
  (
    key: "Omega",
    short: $Omega$,
    description: [The discrete image space comprised of pixels $x$ with dimensionality $d$],
    group: "Mathematical Notations and Definitions",
  ),
  (
    key: "d",
    short: $"d"$,
    long: [$M times M mapsto RR$],
    description: [A distance function $"d"$ operating on a given metric space $M$ returning a scalar distance value between two points],
    group: "Mathematical Notations and Definitions",
  ),
  (
    key: "I",
    short: $I$,
    long: [${I_1, I_2, dots, I_n}$],
    description: [The set of instances in an image with $n$ connected components. The set of ground truth instances and predicted instances can be denoted with $I_("y")$ and $I_(hat(y))$ respectively.],
    group: "Mathematical Notations and Definitions",
  ),
)
