#import "../utils.typ": todo

= Future Work <future_work>
While this thesis has shown clear avenues for advancements in multi-instance segmentation, there remains work to be done to generalize some of our approaches to diverse data and improve the adoption of our findings into the modern medical image segmentation landscape. 

The state-of-the-art in medical image segmentation is nnU-Net, a framework that automatically adapts model parameters to a given dataset, achieving high segmentation performance out-of-the-box. While we did not use this framework to validate our approaches due to its rigidity, an integration of true, globally precomputed Voronoi tessellation and easily customizable weight maps would provide a valuable addition to the current medical image segmentation landscape.

The impact of weight maps on segmentation performance proved to be inconsistent across datasets, hindering their general-purpose adaptability. While we have shown that they are able to introduce manual corrections to loss biases, more research and experimentation is needed to develop grounded heuristics on weight map construction that take dataset instance statistics into account. An example of this would be the scaling of the adaptive weight hyperparameter $beta$ based on the number of regions as well as the difficulty of an instance's segmentation through a calculation based on foreground and background pixels in a region.

Since region-wise losses offer such a high flexibility in their implementation, adapting the loss signal during training based on the specific segmentation performance within a region could offer even better performance. Approaches that incorporate knowledge about Voronoi regions such as the relative instance size to give more granular feedback to the loss function could further improve the identification of instances that are hard to segment. Furthermore, the knowledge that a regions geometric domain contains precisely one component can be used to adaptively penalize loss functions for the prediction of false instances or oversegmentation. However, more work is needed in order to experimentally evaluate the correct formulations of these approaches.