#import "../utils.typ": todo
= Conclusion <conclusion>
This thesis explored various approaches of using geometric tessellation in multi-instance segmentation networks in order to address a critical shortcoming of many modern medical segmentation solutions: Volumetric biases in loss function dynamics lead to the underperformance of standard global DiceCE loss on the segmentation of smaller instances.

We showed that utilizing Voronoi tessellation to compute connected-component-based regions in ground truth labels provides a flexible paradigm to ensure a model's learning process can be influenced to address this issue. Region-wise loss functions and Voronoi-based weight maps aimed to equalize volumetric bias can improve important segmentation metrics on small yet clinically relevant instances.

Notably, the introduction of $cal(L)_"Voronoi"$ provided consistent improvements on both global, pixel-wise, as well as instance-based segmentation metrics. We recommend the incorporation of such a loss component in addition to the standard global loss in order to improve small instance segmentation in addition to keeping the global image context present in the network's learning mechanism. While the balance of global- and region-wise loss weights plays an important role and needs to be explored on a per-dataset basis, assigning equal importance to both components provides a way to improve general segmentation performance on all tested datasets.

Region-wise weight maps aimed at providing an efficient, precomputable way to steer model behaviour during training resulted in generally increased segmentation performance in some datasets. They however have little effect on other datasets or can even be detrimental to the learning process. This is likely due to the vast differences in dataset statistics, leading to weight maps that are well-suited for some applications but not others.

Across our experimentation we have repeatedly confirmed and extended the claim in recent academic literature that the modern standard of the global DiceCE loss function is often detrimental to the segmentation of volumetrically smaller lesions in multi-instance settings, an effect that proved consistent and pronounced in 2D as well as 3D. The importance of evaluating a model's segmentation performance across instance volumes specifically in medical image segmentation cannot be overstated. Both global and instance-wise metrics often fail to capture the nuances of this volumetric bias when instance size is not taken into account. Our research shows that the model's learning process needs to be adapted to the specific task and offers several concrete avenues for improving multi-instance segmentation in the medical domain.